name: Maven Build Java
on:
  workflow_call:
    inputs:
      version:
        description: "Versão da Build"
        required: false
        type: "string"
jobs:
  prepare:
    name: Prepare Execution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      env:
        URL_API: ${{ secrets.URL_API }}
     
  
