name: Sync Workflow to New Repos

on:
  repository:
    types: [created]

jobs:
  sync-workflows:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout central repo
      uses: actions/checkout@v3

    - name: Push workflows to new repo
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git clone https://x-access-token:${GH_TOKEN}@github.com/${{ github.event.repository.full_name }} new-repo
        cd new-repo
        cp -R ../.github .
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .github
        git commit -m "Add default workflows"
        git push
